on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$REPO_NAME/networthnavigator:${{ github.sha }} .
        docker push ghcr.io/$REPO_NAME/networthnavigator:${{ github.sha }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.5.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

    - name: Deploy to Google Cloud Run
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        gcloud run deploy networthnavigator --image ghcr.io/$REPO_NAME/networthnavigator:${{ github.sha }} --region us-central1 --platform managed --allow-unauthenticated